version: '3.8'

services:
  fan_control:
    image: FanControlX
    container_name: fan_control
    privileged: true   # Give the container necessary permissions
    volumes:
      - /dev/ipmi0:/dev/ipmi0  # Mount the IPMI device from the host
      - /dev/ipmi1:/dev/ipmi1
    restart: unless-stopped   # Ensure the container restarts on failure or host reboot
